# Streamlit Cloud Secrets Template
# Copy this content to your Streamlit Cloud secrets configuration

# OPENAI_API_KEY = "your-openai-api-key-here"

# Instructions:
# 1. After deploying to Streamlit Cloud, go to your app settings
# 2. Click on "Secrets" in the left sidebar
# 3. Paste your actual OpenAI API key in this format:
# OPENAI_API_KEY = "sk-proj-your-actual-key-here"
